package hello;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.CrossOrigin;

import hello.Event;
import hello.EventRepository;

@Controller    // This means that this class is a Controller
@CrossOrigin(origins = "http://localhost:8080")
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
	           // Which is auto-generated by Spring, we will use it to handle the data
	private EventRepository EventRepository;
	
	@GetMapping(path="/add") // Map ONLY GET Requests

	public @ResponseBody String addNewEvent (@RequestParam String title
			, @RequestParam String duration, @RequestParam String location, @RequestParam String speaker,
											 @RequestParam String category) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request
		
		Event n = new Event();
		n.setTitle(title);
		n.setDuration(duration);
		n.setLocation(location);
		n.setSpeaker(speaker);
		n.setCategory(category);
		EventRepository.save(n);
		return "Saved";
	}
	
	@GetMapping(path="/all")
	public @ResponseBody Iterable<Event> getAllEvents() {
		// This returns a JSON or XML with the Events
		return EventRepository.findAll();
	}
}
